name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.repository_owner == 'openstack-kr'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Python dependencies and tox
        run: |
          python -m pip install --upgrade pip
          sudo apt install python-tox
      - name: Docs Lint and Sphinx build with tox
        run: tox
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_OCEAN_0BB043E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "doc/build/html" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
